Reduce trade log range if block wasn't found (#838)
While running the withdraw service we saw some alerts of the form:
```
ProviderError: One of the blocks specified in filter (fromBlock, toBlock or blockHash) cannot be found
```
The issue always occurred the first time this function was called.

This could happen if for example the node is load balanced and not all nodes behind the load balancer have the same latest block number. Possibly also if a reorg happened. 

### Test Plan

I don't know how to trigger the issue, so we'll have to test it live.
No regressions: I tried the withdraw script with Infura again on mainnet:
```
$ npx hardhat withdraw --network mainnet --dry-run --receiver 0x6C642caFCbd9d8383250bb25F67aE409147f78b2 
Using account 0x627306090abaB3A6e1400e9345bC60c78a8BEf57
ailed to process events from block 12593265 to latest, reducing range...
Processed events from block 12593265 to 12941476
Failed to process events from block 12941477 to latest, reducing range...
Failed to process events from block 12941477 to 13115582, reducing range...
Processed events from block 12941477 to 13028529
Processed events from block 13028530 to 13115582
Failed to process events from block 13115583 to latest, reducing range...
Processed events from block 13115583 to 13202637
Processed events from block 13202638 to latest
...
```