Allow changing manager (#407)
This PR adds a `setManager` method to the allow list authenticator.

I had originally wanted to just use the `Ownable` contract from OpenZeppelin, but this causes ABI conflicts with the proxy contract from the `hardhat-deploy` plugin:
```
Error: function "owner" will shadow "owner". Please update code to avoid conflict.
```

### Test Plan

Added some new tests.