implement order decoding (#112)
Fixed #95

This PR implements order decoding in a mostly gas efficient way. Specifically:
- Orders are tightly packed to save on call data costs (see #30 for rational behind this)
- Order decoding does not allocate memory - this is important as memory costs grow quadratically so it would be nice if the memory complexity was not `O(n)`. 

### Test Plan

Added new unit tests. In order to verify that my assumptions about solidity memory are correct, I made the following change to the `decodeOrder` function:

```diff
diff --git a/src/contracts/GPv2Settlement.sol b/src/contracts/GPv2Settlement.sol
index 89b0dba..34af9df 100644
--- a/src/contracts/GPv2Settlement.sol
+++ b/src/contracts/GPv2Settlement.sol
@@ -210,6 +210,8 @@ contract GPv2Settlement {
 
         require(encodedOrder.length == ORDER_STRIDE, "malformed order data");
 
+        bytes memory foo = new bytes(10);
+
         sellAmount = uint112(abi.decode(encodedOrder[0:], (uint256)) >> 144);
         buyAmount = uint112(abi.decode(encodedOrder[14:], (uint256)) >> 144);
         validTo = uint32(abi.decode(encodedOrder[28:], (uint256)) >> 224);
```

And ran the memory test again:
```
  GPv2Settlement
    decodeOrder
      1) should not allocate memory


  0 passing (808ms)
  1 failing

  1) GPv2Settlement
       decodeOrder
         should not allocate memory:

      AssertionError: Expected "64" to be equal 0
      + expected - actual

       {
      -  "_hex": "0x00"
      +  "_hex": "0x40"
         "_isBigNumber": true
       }

      at Context.<anonymous> (test/GPv2Settlement.test.ts:230:17)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```